[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
;设置规则标志位
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🍃 Purify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 GoogleCN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/GoogleCN.list
ruleset=📢 GoogleCN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📢 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/GoogleEarth.list
ruleset=📢 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Google.list
ruleset=📢 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=⏬ Download,http://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/Dowload.list
ruleset=Ⓜ️ Onedrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎧 ASMR,https://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/ASMR-ONE.list
ruleset=❤ Ecchi,https://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/Ecchi.list
ruleset=🏰 Bahamut,https://raw.githubusercontent.com/lolikon3000/Rules/refs/heads/main/Ruleset/Bahamut.list
ruleset=🌸 Sakura,https://raw.githubusercontent.com/lolikon3000/Rules/main/Ruleset/YinHua%20Anime.list
ruleset=🍉 Melon,https://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/Melon-Ani.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=👾 Discord,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Discord.list
ruleset=💬 OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🎶 Netease,https://raw.githubusercontent.com/lolikon3000/Clash/main/Ruleset/NetEaseMusic.list
ruleset=🎮 Accelerators,https://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/Accelerators.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/Steam_games.list
ruleset=🎮 Riot,https://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/Riot.list
ruleset=🎮 Epic,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 Origin,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 Sony,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 Nintendo,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎮 Hoyoverse,https://raw.githubusercontent.com/lolikon3000/Rules/refs/heads/main/Ruleset/Hoyoverse.list
ruleset=🎮 Seasun,https://raw.githubusercontent.com/lolikon3000/Rules/main/Ruleset/Amazing%20Seasun.list
ruleset=🎮 Nikke,https://raw.githubusercontent.com/lolikon3000/Rules_Clash/refs/heads/main/Ruleset/Nikke.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 Domestic,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 Aboard,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 Groups,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 Direct,[]GEOIP,LAN
ruleset=🎯 Direct,[]GEOIP,CN
ruleset=🐟 Fugitive,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 Groups`select`[]♻️ Auto`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=🚀 Manual`select`.*
custom_proxy_group=♻️ Auto`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌍 Aboard`select`[]🚀 Groups`[]♻️ Auto`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=🌏 Domestic`select`[]DIRECT`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🚀 Manual
custom_proxy_group=⏬ Download`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=📢 GoogleCN`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=📢 Google`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=Ⓜ️ Onedrive`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎧 ASMR`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=❤ Ecchi`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=🏰 Bahamut`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=🌸 Sakura`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=🍉 Melon`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=👾 Discord`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=💬 OpenAi`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=📹 Youtube`select`[]🚀 Groups`[]♻️ Auto`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual`[]DIRECT
custom_proxy_group=🎮 Accelerators`select`[]REJECT`[]DIRECT
custom_proxy_group=🎮 Steam`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Riot`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Epic`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Origin`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Sony`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Nintendo`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Hoyoverse`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Seasun`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🎮 Nikke`select`[]DIRECT`[]🚀 Groups`[]🇺🇲 United States`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=📺 Bilibili`select`[]🎯 Direct`[]🇨🇳 Taiwan`[]🇭🇰 HongKong
custom_proxy_group=🎶 Netease`select`[]DIRECT`[]🚀 Groups`[]♻️ Auto`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 Direct`select`[]DIRECT`[]🚀 Groups`[]♻️ Auto
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 Purify`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 Fugitive`select`[]🚀 Groups`[]♻️ Auto`[]DIRECT`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 United States`[]🇰🇷 Korea`[]🚀 Manual
custom_proxy_group=🇭🇰 HongKong`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Japan`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 United States`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 Taiwan`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 Singapore`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 Korea`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck








